[package]
name = "atrea-collector"
version = "0.1.0"
edition = "2021"

[features]
default = ["irc"]
irc = []
eventsub = ["dep:tungstenite"]

[dependencies]
openssl = "0.10.71"
pico-args = "0.5.0"
tungstenite = {version = "0.26.2", optional = true}
