[package]
name = "atrea-collector"
version = "0.7.0"
edition = "2021"

[features]
default = ["irc"]
irc = []
eventsub = ["dep:tungstenite"]

[dependencies]
openssl = "0.10"
pico-args = "0.5"
tungstenite = {version = "0.26", optional = true}
